name: CI Workflow
#this is first CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        maven-version: '3.8.5'

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run Tests
      run: mvn test
