name: CI Workflow
#this is first CI
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2    
      

    - name: Build with Maven
      run: |
           mvn -B clean package --file pom.xml
           echo ${{ github.workspace }}
           mkdir artifacts && sudo cp -R target/*.war artifacts
           #sudo cp -R Spring3HibernateApp.war ${{ github.workspace }}/artifacts
           cd artifacts && ls

    # -name: make folder to keep artifacts
    #  run: mkdir artifacts && cp /target/*.war 
    #        cd artifacts && ls 

    - name: save artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: github actions artifacts
          path: artifacts

    - name: Run Tests
      run: mvn test
